export interface Skill {
  id: string;
  name: string;
  unlocked: boolean;
  icon: string;
  category: string;
  position: number;
}

export const initialSkills: Skill[] = [
  {
    id: "1",
    name: "React",
    unlocked: true,
    icon: "⚛️",
    category: "Frontend",
    position: 0,
  },
  {
    id: "2",
    name: "Next.js",
    unlocked: true,
    icon: "▲",
    category: "Frontend",
    position: 1,
  },
  {
    id: "3",
    name: "TypeScript",
    unlocked: true,
    icon: "📘",
    category: "Language",
    position: 2,
  },
  {
    id: "4",
    name: "Node.js",
    unlocked: true,
    icon: "🟢",
    category: "Backend",
    position: 3,
  },
  {
    id: "5",
    name: "PostgreSQL",
    unlocked: true,
    icon: "🐘",
    category: "Database",
    position: 4,
  },
  {
    id: "6",
    name: "AWS",
    unlocked: false,
    icon: "☁️",
    category: "Cloud",
    position: 5,
  },
  {
    id: "7",
    name: "Docker",
    unlocked: true,
    icon: "🐳",
    category: "DevOps",
    position: 6,
  },
  {
    id: "8",
    name: "Python",
    unlocked: true,
    icon: "🐍",
    category: "Language",
    position: 7,
  },
  {
    id: "9",
    name: "MongoDB",
    unlocked: true,
    icon: "🍃",
    category: "Database",
    position: 8,
  },
  {
    id: "10",
    name: "GraphQL",
    unlocked: false,
    icon: "🕸️",
    category: "API",
    position: 9,
  },
  {
    id: "11",
    name: "Kafka",
    unlocked: false,
    icon: "🧩",
    category: "Streaming",
    position: 10,
  },
  {
    id: "12",
    name: "Redis",
    unlocked: false,
    icon: "🟥",
    category: "Cache",
    position: 11,
  },
  {
    id: "13",
    name: "Tailwind",
    unlocked: true,
    icon: "🎨",
    category: "CSS",
    position: 12,
  },
  {
    id: "14",
    name: "Vue.js",
    unlocked: false,
    icon: "🟩",
    category: "Frontend",
    position: 13,
  },
  {
    id: "15",
    name: "Express",
    unlocked: true,
    icon: "⚡",
    category: "Backend",
    position: 14,
  },
  {
    id: "16",
    name: "Git",
    unlocked: true,
    icon: "🌿",
    category: "VCS",
    position: 15,
  },
  {
    id: "17",
    name: "Firebase",
    unlocked: true,
    icon: "🔥",
    category: "Cloud",
    position: 16,
  },
  {
    id: "18",
    name: "Jest",
    unlocked: true,
    icon: "🃏",
    category: "Testing",
    position: 17,
  },
  {
    id: "19",
    name: "Figma",
    unlocked: true,
    icon: "🎭",
    category: "Design",
    position: 18,
  },
  {
    id: "20",
    name: "Linux",
    unlocked: false,
    icon: "🐧",
    category: "OS",
    position: 19,
  },
  {
    id: "21",
    name: "Zustand",
    unlocked: true,
    icon: "🦦",
    category: "State Management",
    position: 20,
  },
  {
    id: "22",
    name: "React Query",
    unlocked: true,
    icon: "🔄",
    category: "State Management",
    position: 21,
  },
  {
    id: "23",
    name: "Prisma",
    unlocked: true,
    icon: "🌐",
    category: "ORM",
    position: 22,
  },
  {
    id: "24",
    name: "Supabase",
    unlocked: true,
    icon: "🧪",
    category: "Backend",
    position: 23,
  },
  {
    id: "25",
    name: "Vercel",
    unlocked: true,
    icon: "▲",
    category: "Deployment",
    position: 24,
  },
  {
    id: "26",
    name: "CI/CD",
    unlocked: false,
    icon: "🔁",
    category: "DevOps",
    position: 25,
  },
  {
    id: "27",
    name: "Kubernetes",
    unlocked: false,
    icon: "☸️",
    category: "DevOps",
    position: 26,
  },
  {
    id: "28",
    name: "Jenkins",
    unlocked: false,
    icon: "🔧",
    category: "DevOps",
    position: 27,
  },
  {
    id: "29",
    name: "MySQL",
    unlocked: true,
    icon: "🐬",
    category: "Database",
    position: 28,
  },
  {
    id: "30",
    name: "Bootstrap",
    unlocked: true,
    icon: "📦",
    category: "CSS",
    position: 29,
  },
  {
    id: "31",
    name: "Sass",
    unlocked: true,
    icon: "💅",
    category: "CSS",
    position: 30,
  },
  {
    id: "32",
    name: "Recoil",
    unlocked: false,
    icon: "🧬",
    category: "State Management",
    position: 31,
  },
  {
    id: "33",
    name: "WebSockets",
    unlocked: true,
    icon: "🔌",
    category: "API",
    position: 32,
  },
  {
    id: "34",
    name: "Nginx",
    unlocked: false,
    icon: "🧱",
    category: "Server",
    position: 33,
  },
  {
    id: "35",
    name: "Storybook",
    unlocked: true,
    icon: "📖",
    category: "Testing",
    position: 34,
  },
];
